apiVersion: v1
kind: Pod
metadata:
  name: netcheck
  namespace: default
spec:
  containers:
    - name: netcheck
      image: alpine:3.19
      command: ["sh", "-c", "apk add --no-cache busybox-extras && sleep 36000"]
