apiVersion: v1
kind: Secret
metadata:
  name: mf-minio-creds
  namespace: argo
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
  AWS_ENDPOINT_URL_S3: "http://minio.minio.svc.cluster.local:9000"
